### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by mrkkrp** [vyorkin/ormolu.el#3]
I think it would be nice to add this one to MELPA.

**Comment by david-christiansen** [comment]
Additionally, the Quelpa README states (as of 6 days ago) that Quelpa is no longer developed, and it encourages users to migrate to something else.

Would you be open to someone else doing the work of MELPA inclusion?

**Comment by vyorkin** [comment]
Sorry for the delay, I didn't watch this repo (for some reason). I'll open a PR to MELPA in a minute and post the link here.

**Comment by vyorkin** [comment]
https://github.com/melpa/melpa/pull/6567

I'll update the README when the recipe-PR is merged

**Comment by vyorkin** [comment]
It is on MELPA now
